# Docker Compose configuration for development
version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: xp-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8080
      - VITE_APP_NAME=XP Frontend Development
      - VITE_APP_VERSION=dev
    networks:
      - xp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  xp-network:
    driver: bridge