version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: xp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis/redis-simple.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - xp-network

  # Optional: Redis Commander UI for monitoring
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: xp-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - xp-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  xp-network:
    driver: bridge